### ISSUE TITLE
Unable to send reason as part of the response

### ISSUE THREAD

**Issue by corrjo** [gene1wood/cfnresponse#1]
Hi, I made a PR against the awslabs repo to add this, will this repo receive downstream changes from that repo?

**Comment by gene1wood** [comment]
@corrjo No, this repo won't automatically get changes from that repo. If, when your PR is merged you open an issue here (at which point the command `if [ "$(curl -s https://raw.githubusercontent.com/awslabs/aws-cloudformation-templates/master/aws/services/CloudFormation/MacrosExamples/StackMetrics/lambda/cfnresponse.py | sha256sum)" = "$(curl -s https://raw.githubusercontent.com/gene1wood/cfnresponse/master/cfnresponse/__init__.py | sha256sum)" ]; then echo "Files match"; fi` will no longer show `Files match`) I can pull the changes and update the pypi package.

**Comment by fraghag** [comment]
What happened with this? I still don't see a parameter for `reason`. Just referring to the cloudwatch log as it does now is not always helpful. For example if one of our custom resource lambdas fails during deployment everything is rolled back, which means that the custom resource lambda loggroup is deleted.

**Comment by corrjo** [comment]
Looks like my PR was never merged https://github.com/awslabs/aws-cloudformation-templates/pull/199

**Comment by gene1wood** [comment]
Indeed, you can compare the upstream with this repo by running

```
if [ "$(curl -s https://raw.githubusercontent.com/awslabs/aws-cloudformation-templates/master/aws/services/CloudFormation/MacrosExamples/StackMetrics/lambda/cfnresponse.py | sha256sum)" = "$(curl -s https://raw.githubusercontent.com/gene1wood/cfnresponse/master/cfnresponse/__init__.py | sha256sum)" ]; then echo "Files match"; fi
```

and see that the upstream has not changed.
