### ISSUE TITLE
Licensing fixed on original

### ISSUE THREAD

**Issue by hyandell** [gene1wood/cfnresponse#8]
Hi Gene,

I'm a part of the AWS Open Source Program office.

I noticed this repo a little while back and was surprised by the "AWS Customer Agreement" text. Digging up the original code on the https://github.com/awslabs/aws-cloudformation-templates/ repository I was doubly surprised to find that was the licensing there, so I've worked with that repository to relicense it under Apache-2.0.

I don't know of your use case for your repository, but I wanted to let you know you can relicense your code over to Apache-2.0 if you so wish :)

https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/CloudFormation/MacrosExamples/StackMetrics/lambda/cfnresponse.py

**Comment by gene1wood** [comment]
Thanks very much, I've set the license here to match the upstream license in defcc5aa24c11776d2f51004455f4e0b46846ce9

**Comment by hyandell** [comment]
Looks good.

Reminder to update the source header of the __init.py file too.

**Comment by gene1wood** [comment]
Good catch, thank you. I've updated the license text inside the module in 2c1ff396a933f3a12fe91ed78141963965905183

I've released a [new version](https://github.com/gene1wood/cfnresponse/releases/tag/v1.1.2) to PyPi, [v1.1.2](https://pypi.org/project/cfnresponse/1.1.2/) with the new license file, source header and PyPi trove classifier (with the new license).

**Comment by hyandell** [comment]
Awesome - thank you Gene :)
